application:
  subdomain: cryptgeon
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://cryptgeon-app:8000/

services:
  redis:
    image: registry.lazycat.cloud/czyt/library/redis:519f0189dfdee3bc
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data

  cryptgeon-app:
    #  cupcakearmy/cryptgeon:2.9.2
    image: registry.lazycat.cloud/czyt/cupcakearmy/cryptgeon:a0b2ad4d22c8711c
    environment:
      - SIZE_LIMIT=4 MiB
    depends_on:
      - redis
    healthcheck:
      test:
        - CMD-SHELL
        - "curl --fail http://127.0.0.1:8000/api/live/"
      start_period: 30s
